### PR TITLE
Implement run configuration for story files

### PR DESCRIPTION
**Pull request by rovner**

### CODE REVIEW

**Comment by stefanschenk** [comment]
I will review and merge this today

**Comment by rovner** [comment]
@stefanschenk Hi! Did you have a chance to review it? I've also pushed some fixes recently.

**Comment by stefanschenk** [comment]
Hi @rovner  My apologies. I have been busy with some other projects. I will look at your fixes today and create a new release with your changes.

**Comment by stefanschenk** [comment]
Hi @rovner, 

I checked your pull request locally and I cannot merge yet at this moment.

I had the plugin development done in IntelliJ Community 2016.3. Some changes in your pull request cannot be build in IntelliJ 2016.

When I switched to 2017.3.x I was able to build the plugin including your changes. 
However, the plugin build with IntelliJ 2017.3 cannot be used in IntelliJ 2016.x

There are two options. We can check if your changes can be made within IntelliJ 2016. Or I can release a plugin with the requirement (since-build) of 2017 and up.

There is however some regression if the plugin is used in 2017.x, the plugin will not find any Step definitions. So I have to look into that. And I would prefer not te release a plugin where step definitions cannot be found.

Issues found in 2016.3

**JBehaveLineMarkerProvider**
_com.intellij.psi.tree.TokenSet_ does not have WHITE_SPACE
_IconLoader.CachedImageIcon_ has private access
_ProgramRunnerUtil.executeConfiguration(runConfiguration, executor)_ no suitable method found

**Comment by rovner** [comment]
>Some changes in your pull request cannot be build in IntelliJ 2016.

I'll try to take a look if it is possible to build my changes on top of 2016.x next week.

>There is however some regression if the plugin is used in 2017.x, the plugin will not find any Step definitions.

Souns strange, step defenitions works well in my project. Could you provide some example project reproducing the issue?

**Comment by rovner** [comment]
>I'll try to take a look if it is possible to build my changes on top of 2016.x next week.

Loks like it is not so easy to fix runner for 2016.x. For some reason idea just doesn't start running configuration.

>>There is however some regression if the plugin is used in 2017.x, the plugin will not find any Step definitions.

>Souns strange, step defenitions works well in my project. Could you provide some example project reproducing the issue?
Any news? Perhaps you need to wait until indexing your project.

**Pull request closed without merging**
